/**
 * The set of message keys below are used for messages generated by the game
 * engine regardless of which set of cards is used.
 */
export const messageKeys = [
  "title",
  "deck.producers",
  "deck.consumers",
  "action.type.play",
  "action.type.ability",
  "action.type.discard",
  "activity.drawingCards.choice.instructions",
  "activity.drawingCards.explanation",
  "activity.choosingAction.choice.instructions",
  "activity.choosingAction.explanation",
  "activity.takingAction.explanation",
  "choice.action",
  "reason.cardAlreadyInPlay",
  "reason.cardNotInGame",
  "reason.cardNotInPlay",
  "reason.cardExhausted",
  "reason.notOwner",
  "reason.maxProducersInPlay",
  "reason.maxConsumersInPlay",
] as const;
