/**
 * The subset of message keys below are used for messages generated by the game
 * engine regardless of which set of cards is used.
 */
export const messageKeys = [
  "deck.producers",
  "deck.consumers",
  "activity.drawingCards.choice.instructions",
  "activity.choosingAction.choice.instructions",
  "reason.cardAlreadyInPlay",
  "reason.cardNotInGame",
  "reason.cardNotInPlay",
  "reason.cardExhausted",
  "reason.notOwner",
  "reason.maxProducersInPlay",
  "reason.maxConsumersInPlay",
] as const;
