name: CI

on:
  pull_request:
    branches:
      - dev
      - main

env:
  NODE_VERSION: 22

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci

      - run: npx @biomejs/biome ci common server client

  test-client:
    name: Test Client App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci

      - run: npm run build --workspace=client

  test-server:
    name: Test Server App
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SUBMODULE_CI_DEPLOY_KEY }}

      - uses: actions/checkout@v4

      - name: Config git for SSH
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Project
        run: npm ci

      - name: Build App
        run: npm run build --workspace=server

      - name: Run Tests
        run: npm test --workspace=server
