name: CI

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx @biomejs/biome ci common server client

  test:
    name: Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_SUBMODULE_CI_PAT }}
          # FIXME!!! Action doesn't support submodule checkout with deploy key.
          # (See: https://github.com/actions/checkout/issues/287)
          # ssh-key: ${{ secrets.PRIVATE_SUBMODULE_CI_DEPLOY_KEY }}

      # Hack 1 (from https://github.com/actions/checkout/issues/287#issuecomment-3018957939):
      # - name: setup SSH for submodules
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.PRIVATE_SUBMODULE_CI_DEPLOY_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      # - name: init and update submodules
      #   run: |
      #     git submodule sync
      #     git submodule update --init --recursive

      # Hack 2:
      # - uses: webfactory/ssh-agent@v0.9.1                                                                                                                                                                 
      #   with:                                                                                                                                                                                             
      #     ssh-private-key: ${{ secrets.PRIVATE_SUBMODULE_CI_DEPLOY_KEY }}   

      # - name: init and update submodules
      #   run: |
      #     git submodule sync
      #     git submodule update --init --recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json

      - run: npm ci

      - run: npm test
